#
# You can start a development server by running `rake ladle`
#
---
host: localhost
port: 3898
base: dc=example,dc=org
bind_dn: uid=%s,ou=people,dc=example,dc=org # the bind dn should have a %s where the uid goes
admin_bind_dn: uid=admin,ou=people,dc=example,dc=org
admin_password: admin
