---
host: localhost
port: 3897
base: dc=example,dc=org
ssl: false
bind_dn: uid=aa729,ou=people,dc=example,dc=org
password: smada
dn: uid=%s,ou=people,dc=example,dc=org # the bind dn should have a %s where the uid goes
